# Generated by Django 5.0.2 on 2024-03-04 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
